insert into public.lords (fullName, age) values ('Бельфегор',385);
insert into public.lords (fullName, age) values ('Асмодей',189);
insert into public.lords (fullName, age) values ('Верделет',245);
insert into public.lords (fullName, age) values ('Инкубус',478);
insert into public.lords (fullName, age) values ('lord 1',20);
insert into public.lords (fullName, age) values ('lord 2',844);
insert into public.lords (fullName, age) values ('lord 3', 164);
insert into public.lords (fullName, age) values ('lord 4', 124);
insert into public.lords (fullName, age) values ('lord 5',168);
insert into public.lords (fullName, age) values ('lord 6',158);
insert into public.lords (fullName, age) values ('lord 7',741);

insert into public.planets (nameofplanet, lordid) values ('Меркурий',3);
insert into public.planets (nameofplanet, lordid) values ('Венера',5);
insert into public.planets (nameofplanet, lordid) values ('Земля',3);
insert into public.planets (nameofplanet, lordid) values ('Марс',4);
insert into public.planets (nameofplanet, lordid) values ('Юпитер',4);
insert into public.planets (nameofplanet, lordid) values ('Сатурн',1);
insert into public.planets (nameofplanet, lordid) values ('Уран',2);
insert into public.planets (nameofplanet, lordid) values ('Нептун',2);
insert into public.planets (nameofplanet, lordid) values ('Планета 1',2);
insert into public.planets (nameofplanet, lordid) values ('Планета 2',5);
insert into public.planets (nameofplanet, lordid) values ('Планета 3',4);
insert into public.planets (nameofplanet, lordid) values ('Планета 4',7);
insert into public.planets (nameofplanet, lordid) values ('Планета 5',9);
insert into public.planets (nameofplanet, lordid) values ('Планета 6',11);
insert into public.planets (nameofplanet, lordid) values ('Планета 7',1);